### PR TITLE
Trying to get travis build fixed

### PR DESCRIPTION
**Pull request by necrolyte2**
Closes averagehat/subsamplebam#1

Also, hoping this will trigger a travis build

### CODE REVIEW

**Comment by necrolyte2** [comment]
This is very odd. I don't really know why it is doing that

**Comment by averagehat** [comment]
My fork is now working, just a python3 issue with StringIO left:

https://travis-ci.org/averagehat/subsamplebam

**Comment by necrolyte2** [comment]
what the heck. Did you do something to fix it?

**Comment by averagehat** [comment]
nope

**Comment by necrolyte2** [comment]
I'm going to close this pull request. Submit a pull request on your end .... i don't know what is going on haha

**Comment by averagehat** [comment]
I'll do that as soon as I fix the python3 stuff

**Pull request closed without merging**
